# Generated by Django 4.1.3 on 2022-11-08 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_jobpost_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
