# Generated by Django 4.1.3 on 2022-11-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_jobpost_skills_jobpost_reqired_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='reqired_skills',
            new_name='required_skills',
        ),
    ]
