# Generated by Django 4.1.3 on 2022-11-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_rename_reqired_skills_jobpost_required_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='type',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part Time')], default='Full time', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='required_skills',
            field=models.ManyToManyField(to='mainapp.skill'),
        ),
    ]
