# Generated by Django 4.1.3 on 2022-11-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_jobpost_type_alter_jobpost_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='required_skills',
            field=models.ManyToManyField(blank=True, to='mainapp.skill'),
        ),
    ]
